### ISSUE TITLE
testreportcontroller does not inform which answer was wrong.

### ISSUE THREAD

**Issue by rpkarlsson** [h0bb3/Riddler#3]
I believe it would be helpful too see which alternative I answered that was wrong or correct on the questions that I got wrong.

Also showing which alteretives were the correct ones.

**Comment by h0bb3** [comment]
Indeed! However, there is a big risk that correct answers are "saved and reused" by someone and this is something I'd like to avoid. Questions are random, but there is a limit on how many questions I can come up with :P Now at least you need to check the question find a correct answer (and this is also a learning experience). I have toyed with the idea of adding some sort of question hint/comment available in the results view, though this will not be implemented this year.
