### ISSUE TITLE
Entering url to ongoing test shows results.

### ISSUE THREAD

**Issue by rpkarlsson** [h0bb3/Riddler#4]
Entering testix once the exam has been taken but while the exam still is ongoing shows the results.
![screen shot 2015-10-02 at 16 22 05](https://cloud.githubusercontent.com/assets/8580645/10248749/d91916c6-6921-11e5-8f0c-0da2eb170b5f.png)

testreportcontroller.php?student=xx222xx&testix=1

**Comment by h0bb3** [comment]
Good one!

Should be fixed now!
